# test_that("plot_auto_variogram runs without error", {
#   # pts_df <- data.frame(x = runif(10, 0, 100), y = runif(10, 0, 100), value = rnorm(10))
#   # results <- auto_variogram_fit(pts_df)
#   # pts <- prepare_pts(pts_df)
#   # g <- gstat::gstat(formula = value ~ 1, locations = ~ x + y, data = pts_df)
#   vg <- readRDS("data/variogram.rds")
#   vgm_model <- readRDS("data/vgm_model.rds")
#   vfit <- gstat::fit.variogram(vg, model = vgm_model, fit.kappa = FALSE)
#   expect_silent(plot_auto_variogram(vg, vfit))
# })
